### ISSUE TITLE
StationaryBootstrap error

### ISSUE THREAD

**Issue by chaltik** [bashtage/arch#209]
StationaryBootstrap object throws error on construction:

```from arch.bootstrap import StationaryBootstrap

x=np.random.randn(240)

bs=StationaryBootstrap(6,x,random_state=1000)
Traceback (most recent call last):

  File "<ipython-input-238-16dade56bcc3>", line 1, in <module>
    bs=StationaryBootstrap(6,x,random_state=1000)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/arch/bootstrap/base.py", line 968, in __init__
    super(StationaryBootstrap, self).__init__(block_size, *args, **kwargs)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/arch/bootstrap/base.py", line 876, in __init__
    super(CircularBlockBootstrap, self).__init__(*args, **kwargs)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/arch/bootstrap/base.py", line 156, in __init__
    if len(arg) != self._num_items:

TypeError: object of type 'int' has no len()

**Comment by bashtage** [comment]
You cannot set this at initialization.  You can only pass vectors that you want to bootstrap.  

If you want to control the RandomState used by the bootstrap you need to use the `random_state` attribute.

```python
x=np.random.randn(240)
bs=StationaryBootstrap(6,x)
bs.random_state.seed(1000)
```

**Comment by chaltik** [comment]
Thanks for the explanation
