### ISSUE TITLE
Forecast method throws me Memory error and it's extremely slow

### ISSUE THREAD

**Issue by gioxc88** [bashtage/arch#252]
Hello I tried to change my code from a manual simulation to using the forecast method but I have two problems 

1) it gives me Memory Error 

```
Traceback (most recent call last):
  File "C:\Programs\Python\Python37-32\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-34-13ef5da1c1a3>", line 1, in <module>
    sim = mdl_est.forecast(horizon=n_step, method='bootstrap', simulations=n_scen, rng=custom_scenarios)
  File "C:\Programs\Python\Python37-32\lib\site-packages\arch\univariate\base.py", line 1119, in forecast
    return self.model.forecast(params, horizon, start, align, method, simulations, rng)
  File "C:\Programs\Python\Python37-32\lib\site-packages\arch\univariate\mean.py", line 649, in forecast
    simulations=simulations, rng=rng)
  File "C:\Programs\Python\Python37-32\lib\site-packages\arch\univariate\volatility.py", line 537, in forecast
    horizon, simulations, random_state)
  File "C:\Programs\Python\Python37-32\lib\site-packages\arch\univariate\volatility.py", line 336, in _bootstrap_forecast
    start, horizon, simulations, rng)
  File "C:\Programs\Python\Python37-32\lib\site-packages\arch\univariate\volatility.py", line 1023, in _simulation_forecast
    paths = np.zeros((t, simulations, horizon))
MemoryError
```

or

```
Traceback (most recent call last):
  File "C:\Programs\Python\Python37-32\lib\site-packages\IPython\core\interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-43-13ef5da1c1a3>", line 1, in <module>
    sim = mdl_est.forecast(horizon=n_step, method='bootstrap', simulations=n_scen, rng=custom_scenarios)
  File "C:\Programs\Python\Python37-32\lib\site-packages\arch\univariate\base.py", line 1119, in forecast
    return self.model.forecast(params, horizon, start, align, method, simulations, rng)
  File "C:\Programs\Python\Python37-32\lib\site-packages\arch\univariate\mean.py", line 669, in forecast
    long_run_variance_paths = variance_paths.copy()
MemoryError
```

Furthermore if I try to implement manually the simulation process it is extremely fast.
Steps to reproduce my problem where log_ret is a ndarray with shape (504, )

THIS IS MY MANUAL IMPLEMENTATION AND IT WORKS REALLY FAST

```
        #  MODEL ESTIMATION
        n_scen = 10000
        n_step = 20
        mdl = arch_model(log_ret, mean='ARX', lags=1, vol='GARCH', p=1, q=1, dist='t')

        mdl_est = mdl.fit(disp='off', options={'disp': False})
        std_res = (mdl_est.resid / mdl_est.conditional_volatility)[1:]

        sim_idx = np.random.randint(len(log_ret) - 1, size=(n_scen, n_step))
        sim_std_res = std_res[sim_idx]  # simulated standardized residuals

        # initial parameters for simulation
        v_0 = (mdl_est.conditional_volatility[-1]) ** 2
        e_0 = mdl_est.resid[-1]
        r_0 = log_ret[-1, a]

        param = mdl_est.params[:-1].values
        sim_log_ret = np.zeros(sim_std_res.shape)

        for k in range(n_scen):
            v_t = v_0
            e_t = e_0
            r_t = r_0
            for j in range(n_step):
                v_t = param[2] + param[3] * e_t ** 2 + param[4] * v_t
                e_t = (v_t ** 0.5) * sim_std_res[k, j]
                sim_log_ret[k, j] = param[0] + param[1] * r_t + e_t
                r_t = sim_log_ret[k, j]

        scenarios_n_step_ahead = np.sum(sim_log_ret, axis=1) / 100

```

THIS IS THE SAME AS ABOVE BUT USING FORECAST

```
        #  MODEL ESTIMATION
        n_scen = 10000
        n_step = 20
        mdl = arch_model(log_ret, mean='ARX', lags=1, vol='GARCH', p=1, q=1, dist='t')

        mdl_est = mdl.fit(disp='off', options={'disp': False})
        sim = mdl_est.forecast(horizon=n_step, method='bootstrap', simulations=n_scen)

        scenarios_n_step_ahead = sim.simulations.values[-1, :, -1]/ 100

```

Thank you for your help.
Best regards

**Comment by bashtage** [comment]
The temporary arrays are n_scen  by n_step by nobs, which is pretty big in your case.   It is fairly general purpose and so returns arrays that are nan-filled even when you only want the last forecast.   This is why is it slower than a direct implementation of only a single forecast.

**Comment by bashtage** [comment]
`forecast` is allocating a lot of unnecessary memory.  This is done to simplify the general purpose implementation, but can really hurt performance if only interested in 1 (or a few) forecasts at the end of the sample.

**Comment by gioxc88** [comment]
Yes the main problem is that I am developing a package that makes massive use of your package.
But if I cannot make use of the forecast method it is a great pain to handle every single supported model outside.

Furthermore the scipy otptimize minimize function used to maximize the likelihood is very unstable.
I will open another issuse but just to anticipate something there are several times when even scaling returns by 100 is not enough. You need to scale for 1000 or more. I would suggest that you handle this internally using some kind of logic that scales automatically the input series before minimizing the likelihood. In Matlab for example I never had problem of convergence.
Or maybe try to use another optimization package like cvx?

This package has a great potential and it is the main reason that made me switch to Python.
For financial time series analysis is a must. I hope this problems could be solved sooner or later.

Thank you prof. Sheppard!
