### ISSUE TITLE
ADF raises LinAlgError

### ISSUE THREAD

**Issue by delyanr** [bashtage/arch#262]
Hello! I'm trying to convert some of my code from `statsmodels` to your `arch` package since it is generally faster for my purposes. However, while doing so I encountered an error with the ADF test. See code below:

```
import numpy as np
from arch.unitroot import ADF
x = np.asarray([0., 0., 0., 0., 0., 0., 1., 1., 0., 0.])
ADF(x)
```

Which leads to the following exception:

```
Traceback (most recent call last):

  File "c:\anaconda3\lib\site-packages\IPython\core\formatters.py", line 702, in __call__
    printer.pretty(obj)

  File "c:\anaconda3\lib\site-packages\IPython\lib\pretty.py", line 402, in pretty
    return _repr_pprint(obj, self, cycle)

  File "c:\anaconda3\lib\site-packages\IPython\lib\pretty.py", line 697, in _repr_pprint
    output = repr(obj)

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 343, in __repr__
    return str(type(self)) + '\n"""\n' + self.__str__() + '\n"""'

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 340, in __str__
    return self.summary().__str__()

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 417, in summary
    table_data = [('Test Statistic', '{0:0.3f}'.format(self.stat)),

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 403, in stat
    self._compute_if_needed()

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 367, in _compute_if_needed
    self._compute_statistic()

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 616, in _compute_statistic
    self._select_lag()

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 610, in _select_lag
    low_memory=self._low_memory)

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 271, in _df_select_lags
    ic_best, best_lag = _autolag_ols(lhs, full_rhs, start_lag, max_lags, method)

  File "c:\anaconda3\lib\site-packages\arch\unitroot\unitroot.py", line 211, in _autolag_ols
    b = solve(r[:i, :i], qpy[:i])

  File "c:\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 377, in solve
    _assertNdSquareness(a)

  File "c:\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 211, in _assertNdSquareness
    raise LinAlgError('Last 2 dimensions of the array must be square')

LinAlgError: Last 2 dimensions of the array must be square
```

While I was expecting this:

```
import numpy as np
from statsmodels.tsa.stattools import adfuller
x = np.asarray([0., 0., 0., 0., 0., 0., 1., 1., 0., 0.])
adfuller(x)

(-2.23606797749979,
 0.19341617825473173,
 1,
 8,
 {'1%': -4.6651863281249994, '5%': -3.3671868750000002, '10%': -2.802960625},
 -138.6577425070096)
```

Could it be that I'm doing something wrong? Any help would be appreciated.

Many thanks,
Delyan

P.S. The relevant details of my environment are:

```
Windows 10 OS

python 3.6
numpy 1.14.5
arch 4.7.0
statsmodels 0.9.0
```

**Comment by bashtage** [comment]
The autolag selection was choosing a lag that was too large.  This is fixed in master and will be in the next release.
