### ISSUE TITLE
Cannot build python wheel

### ISSUE THREAD

**Issue by mboisson** [bashtage/arch#273]
Hi,
For our HPC site, we are building python wheels for compiled packages, to make it easier to install by our users. This package gives an error when trying to build a wheel : 

``` 
build_python-2.7) [mboisson@build-node arch-4.7.0]$ python setup.py bdist_wheel
running bdist_wheel
Traceback (most recent call last):
  File "setup.py", line 189, in <module>
    run_setup(binary=build_binary)
  File "setup.py", line 180, in run_setup
    for key in SETUP_REQUIREMENTS],
  File "/home/mboisson/wheels/tmp.18781/build_python-2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/mboisson/wheels/tmp.18781/build_python-2.7/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 188, in run
    build_ext = self.reinitialize_command('build_ext')
  File "/home/mboisson/wheels/tmp.18781/build_python-2.7/lib/python2.7/site-packages/setuptools/__init__.py", line 198, in reinitialize_command
    cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/cmd.py", line 319, in reinitialize_command
    command, reinit_subcommands)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 925, in reinitialize_command
    command = self.get_command_obj(command_name)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
    cmd_obj = self.command_obj[command] = klass(self)
TypeError: object() takes no parameters
```

**Comment by mboisson** [comment]
Actually, it even fails to just "install" : 
``` 
(test_arch) [mboisson@build-node wheels]$ pip install arch
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting arch
  Using cached https://files.pythonhosted.org/packages/74/ec/7767bc6d6f48c7048ab0145d16a354320f33990c0abcca1710c69aeb1456/arch-4.7.0.tar.gz
Collecting statsmodels>=0.8 (from arch)
Collecting scipy>=0.19 (from arch)
Collecting numpy>=1.12 (from arch)
Collecting pandas>=0.20 (from arch)
Collecting cached_property>=1.5.1 (from arch)
Collecting patsy (from statsmodels>=0.8->arch)
  Downloading https://files.pythonhosted.org/packages/ea/0c/5f61f1a3d4385d6bf83b83ea495068857ff8dfb89e74824c6e9eb63286d8/patsy-0.5.1-py2.py3-none-any.whl (231kB)
    100% |████████████████████████████████| 235kB 7.9MB/s
Collecting pytz>=2011k (from pandas>=0.20->arch)
Collecting python-dateutil>=2.5.0 (from pandas>=0.20->arch)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 17.7MB/s
Collecting six (from patsy->statsmodels>=0.8->arch)
Building wheels for collected packages: arch
  Running setup.py bdist_wheel for arch ... error
  Complete output from command /home/mboisson/wheels/test_arch/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lBMtBV/arch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-NFza7z --python-tag cp27:
  running bdist_wheel
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-lBMtBV/arch/setup.py", line 189, in <module>
      run_setup(binary=build_binary)
    File "/tmp/pip-install-lBMtBV/arch/setup.py", line 180, in run_setup
      for key in SETUP_REQUIREMENTS],
    File "/home/mboisson/wheels/test_arch/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/mboisson/wheels/test_arch/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 188, in run
      build_ext = self.reinitialize_command('build_ext')
    File "/home/mboisson/wheels/test_arch/lib/python2.7/site-packages/setuptools/__init__.py", line 198, in reinitialize_command
      cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/cmd.py", line 319, in reinitialize_command
      command, reinit_subcommands)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 925, in reinitialize_command
      command = self.get_command_obj(command_name)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
      cmd_obj = self.command_obj[command] = klass(self)
  TypeError: object() takes no parameters

  ----------------------------------------
  Failed building wheel for arch
  Running setup.py clean for arch
  Complete output from command /home/mboisson/wheels/test_arch/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lBMtBV/arch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: option --all not recognized

  ----------------------------------------
  Failed cleaning build dir for arch
Failed to build arch
Installing collected packages: numpy, scipy, pytz, six, python-dateutil, pandas, patsy, statsmodels, cached-property, arch
  Running setup.py install for arch ... done
Successfully installed arch-4.7.0 cached-property-1.5.1 numpy-1.16.2 pandas-0.23.4 patsy-0.5.1 python-dateutil-2.8.0 pytz-2018.9 scipy-1.2.1 six-1.12.0 statsmodels-0.9.0
```

**Comment by bashtage** [comment]
What version of setuptools are you using?

**Comment by bashtage** [comment]
I can't repro using setuptools 40.8.0 which is latest on 2.7.15.

**Comment by mboisson** [comment]
```
(build_arch) [mboisson@build-node wheels]$ pip list
Package    Version
---------- -------
numpy      1.16.2
pip        18.1
setuptools 40.8.0
wheel      0.33.1
(build_arch) [mboisson@build-node wheels]$ pip wheel arch
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Collecting arch
  Using cached https://files.pythonhosted.org/packages/74/ec/7767bc6d6f48c7048ab0145d16a354320f33990c0abcca1710c69aeb1456/arch-4.7.0.tar.gz
Collecting statsmodels>=0.8 (from arch)
  File was already downloaded /home/mboisson/wheels/statsmodels-0.9.0-cp27-cp27mu-linux_x86_64.whl
Collecting scipy>=0.19 (from arch)
  File was already downloaded /home/mboisson/wheels/scipy-1.2.1-cp27-cp27mu-linux_x86_64.whl
Collecting numpy>=1.12 (from arch)
  File was already downloaded /home/mboisson/wheels/numpy-1.16.2-cp27-cp27mu-linux_x86_64.whl
Collecting pandas>=0.20 (from arch)
  Using cached https://files.pythonhosted.org/packages/81/fd/b1f17f7dc914047cd1df9d6813b944ee446973baafe8106e4458bfb68884/pandas-0.24.1.tar.gz
Collecting cached_property>=1.5.1 (from arch)
  File was already downloaded /home/mboisson/wheels/cached_property-1.5.1-py2.py3-none-any.whl
Collecting patsy (from statsmodels>=0.8->arch)
  File was already downloaded /home/mboisson/wheels/patsy-0.5.1-py2.py3-none-any.whl
Collecting python-dateutil>=2.5.0 (from pandas>=0.20->arch)
  File was already downloaded /home/mboisson/wheels/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting pytz>=2011k (from pandas>=0.20->arch)
  File was already downloaded /home/mboisson/wheels/pytz-2018.9-py2-none-any.whl
Collecting six (from patsy->statsmodels>=0.8->arch)
  File was already downloaded /home/mboisson/wheels/six-1.12.0-py2.py3-none-any.whl
Skipping statsmodels, due to already being wheel.
Skipping scipy, due to already being wheel.
Skipping numpy, due to already being wheel.
Skipping cached-property, due to already being wheel.
Skipping patsy, due to already being wheel.
Skipping python-dateutil, due to already being wheel.
Skipping pytz, due to already being wheel.
Skipping six, due to already being wheel.
Building wheels for collected packages: arch, pandas
  Running setup.py bdist_wheel for arch ... error
  Complete output from command /home/mboisson/wheels/build_arch/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-wheel-2jPv8m/arch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-WdzN1F:
  running bdist_wheel
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-wheel-2jPv8m/arch/setup.py", line 189, in <module>
      run_setup(binary=build_binary)
    File "/tmp/pip-wheel-2jPv8m/arch/setup.py", line 180, in run_setup
      for key in SETUP_REQUIREMENTS],
    File "/home/mboisson/wheels/build_arch/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/mboisson/wheels/build_arch/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 188, in run
      build_ext = self.reinitialize_command('build_ext')
    File "/home/mboisson/wheels/build_arch/lib/python2.7/site-packages/setuptools/__init__.py", line 198, in reinitialize_command
      cmd = _Command.reinitialize_command(self, command, reinit_subcommands)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/cmd.py", line 319, in reinitialize_command
      command, reinit_subcommands)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 925, in reinitialize_command
      command = self.get_command_obj(command_name)
    File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/2.7.14/lib/python2.7/distutils/dist.py", line 846, in get_command_obj
      cmd_obj = self.command_obj[command] = klass(self)
  TypeError: object() takes no parameters

  ----------------------------------------
  Failed building wheel for arch
  Running setup.py clean for arch
  Complete output from command /home/mboisson/wheels/build_arch/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-wheel-2jPv8m/arch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help

  error: option --all not recognized

  ----------------------------------------
  Failed cleaning build dir for arch
```

**Comment by bashtage** [comment]
Hmmm.  Any other hints about your environment that I could use to replicate?  What happens if you install Cython before arch?  This shouldn't matter, but grasping at straws.

**Comment by mboisson** [comment]
For whatever reason, installing `Cython` in the build environment did fix the issue. It looks like `Cython` is a missing build dependency of `arch`. I am able to build the wheels now.

**Comment by bashtage** [comment]
I found the issue.  When you build w/o Cython you are building with --no-binary, and so there are no compiled modules built.  This happens since arch is happy to run w/o compilation, which is generally a bad idea unless numba is available, in which case it is as fast as using Cython (probably a bit faster).  This means building your own wheels w/o Cython is going to produce a low-performance wheel.  OTOH, I can't really add Cython to the dependencies since it isn't an actual dependency.

Not totally clear what the right action is here...

For my future reference, the solution is to add 

```
from setuptools.command.build_ext import build_ext as setuptools_build_ext

def run_setup(binary=True):
    if not binary:
        cmdclass['build_ext'] = setuptools_build_ext
```

**Comment by bashtage** [comment]
Fixed in master now.  Building a wheel without Cython is mostly a bad idea since the code may be very slow if build w/o Cython and numba is not available. numba is a runtime import, so it has no impact on building.  If the wheel is build w/o Cython and numba isn't installed, users will now see a `PerformanceWarning`.
